# Generated by Django 4.1.5 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bieterverfahren", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biddingprocess",
            name="invited_bidders",
            field=models.TextField(blank=True, null=True),
        ),
    ]
